import Image from "next/image";
import { notFound } from "next/navigation";
import ids from "../../../data/idsOnSell.json";
import ShareButton from "./ShareButton";

type PageProps = {
  params: Promise<{ slug: string }>;
};

export default async function Page({ params }: PageProps) {
  const { slug } = await params;
  const item: any = ids.find((i) => i.slug === slug);

  if (!item) notFound();

  const siteUrl = "https://mlbbtopup.in";

  // ✅ SINGLE SOURCE OF SHARE TEXT
  const shareText = `🔥 MLBB Account For Sale

${item.title}

🎭 Heroes: ${item.heroes?.total ?? item.heroes}+
🎨 Skins: ${item.skins?.total ?? "N/A"}+
💎 COA: ${item.currencies?.coa ?? item.coa ?? 0}+
${item.heroTitles?.global?.length ? "🌍 Global Hero Available" : ""}

Price: ₹${item.price}

Generated by mlbbtopup.in`;

  return (
    <main className="relative min-h-screen p-6 max-w-4xl mx-auto space-y-8">

      {/* ================= SHARE (TOP RIGHT) ================= */}
      <ShareButton
        text={shareText}
        url={`${siteUrl}/idsonsell/${item.slug}`}
      />

      <p className="text-xs text-center text-gray-500">
        You choose where to share. We only provide representation.
      </p>

      {/* ================= TITLE ================= */}
      <h1 className="text-2xl font-bold">{item.title}</h1>

      {/* ================= IMAGE + PRICE ================= */}
      <div className="flex gap-4 items-start">
        <Image
          src={item.media?.images?.[0] || item.images?.[0] || "/logo.png"}
          alt={item.title}
          width={240}
          height={150}
          className="rounded-lg border object-cover"
        />

        <div className="space-y-2 text-sm">
          <div className="text-xl font-bold">₹{item.price}</div>
          <div>
            Server: <b>{item.account?.server || item.server}</b>
          </div>
          <div>
            Login: <b>{item.account?.loginType || item.loginType}</b>
          </div>
          <div>
            Rebindable:{" "}
            <b>{item.account?.rebindable ? "Yes" : "No"}</b>
          </div>
        </div>
      </div>

      {/* ================= RANK ================= */}
      {item.rank && (
        <section>
          <h2 className="font-semibold mb-2">Rank</h2>
          <div className="grid grid-cols-2 gap-2 text-sm">
            <div>Current: {item.rank.current}</div>
            <div>Highest: {item.rank.highest}</div>
            {item.rank.stars && <div>Stars: {item.rank.stars}</div>}
          </div>
        </section>
      )}

      {/* ================= HERO & SKIN ================= */}
      <section>
        <h2 className="font-semibold mb-2">Heroes & Skins</h2>
        <div className="grid grid-cols-2 gap-2 text-sm">
          <div>Heroes: {item.heroes?.total ?? item.heroes}</div>
          <div>Total Skins: {item.skins?.total}</div>
          <div>Legend Skins: {item.skins?.legend}</div>
          <div>Grand Skins: {item.skins?.grand}</div>
          <div>Epic Skins: {item.skins?.epic}</div>
        </div>

        {item.skins?.collector?.length > 0 && (
          <div className="mt-2 text-sm">
            Collector Skins:
            <ul className="list-disc ml-5">
              {item.skins.collector.map((c: string, i: number) => (
                <li key={i}>{c}</li>
              ))}
            </ul>
          </div>
        )}
      </section>

      {/* ================= CURRENCIES ================= */}
      <section>
        <h2 className="font-semibold mb-2">Currencies</h2>
        <div className="grid grid-cols-2 gap-2 text-sm">
          <div>COA: {item.currencies?.coa ?? item.coa}</div>
          <div>Magic Core: {item.currencies?.magicCore ?? item.magicCore}</div>
          <div className="col-span-2">
            Double Diamonds:
            <b>
              {item.diamonds?.doubleDiamondAvailable?.length > 0
                ? " " + item.diamonds.doubleDiamondAvailable.join(", ")
                : " Not Available"}
            </b>
          </div>
        </div>
      </section>

      {/* ================= DESCRIPTION ================= */}
      <section>
        <h2 className="font-semibold mb-2">Description</h2>
        <p className="text-sm text-gray-700">{item.description}</p>
      </section>

      {/* ================= CTA ================= */}
      <a
        href={item.dealer?.contact?.whatsapp || item.dealer?.contact}
        target="_blank"
        className="block w-full text-center px-6 py-3 rounded-xl bg-black text-white font-semibold"
      >
        Contact Dealer
      </a>

      {/* ================= FOOTER ================= */}
      <div className="text-xs text-center text-gray-500">
        Account ID: {item.id} • Updated{" "}
        {item.meta?.updatedAt || item.updatedAt}
      </div>

    </main>
  );
}
